DROP TABLE IF EXISTS `car` CASCADE;
CREATE TABLE `car` (
    `id` INTEGER UNIQUE PRIMARY KEY AUTO_INCREMENT,
    `car_make` VARCHAR(255) NOT NULL,
    `model` VARCHAR(255) NOT NULL,
    `reg` INTEGER NOT NULL
);